### ISSUE TITLE
xcode14 beta5 用了插件以后可以解决报错问题， 但是安装时候会安装失败， 提示存在相同 bundle id 包

### ISSUE THREAD

**Issue by singleton-altman** [1677/CocoaPods-pod-sign#1]

**Comment by singleton-altman** [comment]
还有一个问题， 在安装了这个插件以后， pob lib lint 会报错。
```
Encountered an unknown error (undefined method `real_path' for nil:NilClass
```

**Comment by 1677** [comment]
方便提供一下你的demo工程么，可以把demo工程放到你的仓库里把地址贴出来就可以了

**Comment by hotwill07** [comment]
同样的问题，报错如下：
This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique.
Domain: com.apple.dt.MobileDeviceErrorDomain

项目中有多个bundle需要前面的，pod脚本如下：

plugin 'cocoapods-pod-sign'

config_pod_bundle_id_and_team_id({
  'Debug' => {:bundle_id => 'com.pods.specDe', :team_id => 'xxxxx'},
  'Release' => {:bundle_id => 'com.pods.specRe', :team_id => 'xxxx'}
})

如此配置之后，所有bundle的bundle_id都是一样的，导致的冲突，有办法解决不？

**Comment by hotwill07** [comment]
> 同样的问题，报错如下： This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique. Domain: com.apple.dt.MobileDeviceErrorDomain
> 
> 项目中有多个bundle需要前面的，pod脚本如下：
> 
> plugin 'cocoapods-pod-sign'
> 
> config_pod_bundle_id_and_team_id({ 'Debug' => {:bundle_id => 'com.pods.specDe', :team_id => 'xxxxx'}, 'Release' => {:bundle_id => 'com.pods.specRe', :team_id => 'xxxx'} })
> 
> 如此配置之后，所有bundle的bundle_id都是一样的，导致的冲突，有办法解决不？


追加：【就是能不能提供一个方法，只修改teamId，bundleId用pods自己生成的】

**Comment by 1677** [comment]
你在Podfile里写的bundle_id就是上面的com.pods.specDe么？
1、如果你的项目只有一个Bundle identifier，只写`plugin 'cocoapods-pod-sign'`这句就可以了。
2、如果你的项目有多个Bundle identifier（如：测试用的企业证书，发布用的正式证书），这时才用config_pod_bundle_id_and_team_id方法来指定，不同的config（Debug，Release就是不同的config）使用不同的Bundle identifier。

看你上面写的不是真实的Bundle identifier和team id。新的Xcode多了一步对资源文件的签名操作，本插件就是帮你在pod install的时候将对应的Bundle identifier与team id设置给pod对应的资源文件里。详细说明可查看我写的[解决Xcode14 pod签名问题](https://www.jianshu.com/p/58d3202411c0)

**Comment by 1677** [comment]
> 还有一个问题， 在安装了这个插件以后， pob lib lint 会报错。
> 
> ```
> Encountered an unknown error (undefined method `real_path' for nil:NilClass
> ```

问题已经修复，可以拉取一下1.1.1版本再试一下。

**Comment by hotwill07** [comment]
> > 同样的问题，报错如下： This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique. Domain: com.apple.dt.MobileDeviceErrorDomain
> > 项目中有多个bundle需要前面的，pod脚本如下：
> > plugin 'cocoapods-pod-sign'
> > config_pod_bundle_id_and_team_id({ 'Debug' => {:bundle_id => 'com.pods.specDe', :team_id => 'xxxxx'}, 'Release' => {:bundle_id => 'com.pods.specRe', :team_id => 'xxxx'} })
> > 如此配置之后，所有bundle的bundle_id都是一样的，导致的冲突，有办法解决不？
> 
> 追加：【就是能不能提供一个方法，只修改teamId，bundleId用pods自己生成的】

<img width="1038" alt="1-1" src="https://user-images.githubusercontent.com/13374960/185274389-84621c12-80b8-4737-ae9f-b4389ba81ca8.png">

<img width="978" alt="1-2" src="https://user-images.githubusercontent.com/13374960/185274415-a16f8262-3853-40cd-bb57-0f3d0b724d44.png">

<img width="1064" alt="1-3" src="https://user-images.githubusercontent.com/13374960/185274450-f1d659a9-690e-486a-a8f5-c60d159e1ab1.png">

不知道这么写 您能明白不？  我项目中有多个bundle需要添加证书，按照您给的方案，所有bundle需要添加证书的bundleid都一样，运行会报错

**Comment by 1677** [comment]
- 对于你说的 “Bundle identifier用pods自己生成的” 理论上不可行，因为pods自己生成的Bundle identifier相同的库生成的Bundle identifier也相同，在别人使用一个pods库A注册过对应的Bundle identifier后你的证书就没法再给这个pods库A注册Bundle identifier了。看你的报错提示有一名Bundle identifiers must be unique，说明你的com.pods.specDe被其他证书注册过了，不是唯一了，所以建议用自己主工程真实的Bundle identifier。

- 很明显com.pods.specDe就不是你们公司App用的Bundle identifier，应该是pods自己生成的。看你的配置你们的项目应该只有一个Bundle identifier。你可以只写这一行这样就会自动从主工程里读取你的Bundle identifier和teamid。
```
plugin 'cocoapods-pod-sign'
```
- config_pod_bundle_id_and_team_id这个方法是给那些有企业证书的工程用的，有企业证书的测试包是一个Bundle identifier，发布是另一个Bundle identifier。看你的配置你应该不需要这个。

最后，如果你的问题解决了请及时在这里回复一下。

**Comment by hotwill07** [comment]
> 
额 已经解决了，podfile 设置：
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEVELOPMENT_TEAM'] = '87CEBRV265'
    end
  end
end

依然感谢！

**Comment by singleton-altman** [comment]
> 

这样的话， 那就不需要用插件了吧

**Comment by hotwill07** [comment]
> 这样的话， 那就不需要用插件了吧

对的，插件需要卸载了

**Comment by hotwill07** [comment]
> * 对于你说的 “Bundle identifier用pods自己生成的” 理论上不可行，因为pods自己生成的Bundle identifier相同的库生成的Bundle identifier也相同，在别人使用一个pods库A注册过对应的Bundle identifier后你的证书就没法再给这个pods库A注册Bundle identifier了。看你的报错提示有一名Bundle identifiers must be unique，说明你的com.pods.specDe被其他证书注册过了，不是唯一了，所以建议用自己主工程真实的Bundle identifier。
> * 很明显com.pods.specDe就不是你们公司App用的Bundle identifier，应该是pods自己生成的。看你的配置你们的项目应该只有一个Bundle identifier。你可以只写这一行这样就会自动从主工程里读取你的Bundle identifier和teamid。
> 
> ```
> plugin 'cocoapods-pod-sign'
> ```
> 
>  * config_pod_bundle_id_and_team_id这个方法是给那些有企业证书的工程用的，有企业证书的测试包是一个Bundle identifier，发布是另一个Bundle identifier。看你的配置你应该不需要这个。
> 
> 最后，如果你的问题解决了请及时在这里回复一下。


额 已经解决了，podfile 设置：
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['DEVELOPMENT_TEAM'] = 'xxxxx'
end
end
end

依然感谢！

**Comment by 1677** [comment]
> 

插件是让你只写一行`plugin 'cocoapods-pod-sign'`就行了不用写额外的代码，会自动提取主工程的信息给pod进行设置。如果你想通过其他方式也可以，可能要写的代码就多了。
