### ISSUE TITLE
Your Podfile requires that the plugin `cocoapods-pod-sign` be installed. Please install it and try installation again.

### ISSUE THREAD

**Issue by ben-ying** [1677/CocoaPods-pod-sign#5]
使用如下命令安装完以后仍然报错 
```sudo gem install cocoapods-pod-sign```
```Your Podfile requires that the plugin `cocoapods-pod-sign` be installed. Please install it and try installation again.```
如果加上skip_pod_bundle_sign，出现如下错误：
<img width="569" alt="image" src="https://user-images.githubusercontent.com/4661175/207205966-901bee1e-0441-4581-8884-b15477f39bf8.png">

**Comment by 1677** [comment]
你第一个错误是执行`pod install`的时候找不到`cocoapods-pod-sign`这个插件，应该是你使用了`sudo`安装的需要超级管理员才能访问这个插件，普通用户没仅限访问这个插件。你第二个错误是`skip_pod_bundle_sign`这个方法被当成变量了，因为这个方法是在`cocoapods-pod-sign`中写的由于`cocoapods-pod-sign`没引用到所以`skip_pod_bundle_sign`也找不到。有以下几个方式解决：
- 方法一：先卸载`cocoapods-pod-sign`然后不加`sudo`再安装一遍。
- 方法二：`pod install`也超级管理员，即`sudo pod instll`。这种方式不推荐可能安装的pod变成超级管理员才能访问，后面其他操作都需要变成超级管理员才行。
- 方法三：使用Gemfile管理插件，1、在Podfile所在的文件夹下执行`bundle init`命令会创建一个Gemfile文件；2、然后写入gem 'cocoapods-pod-sign'；3、写好后再执行`bundle install`命令会自动安装插件。4、最后把原来的`pod install`改成`bundle exec pod install`就可以了。
